# Generated by Django 3.2.1 on 2021-05-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210505_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendinginfo',
            name='checkin',
            field=models.TimeField(blank=True, null=True, verbose_name='checkin'),
        ),
        migrations.AlterField(
            model_name='lendinginfo',
            name='con_after',
            field=models.TextField(blank=True, null=True),
        ),
    ]
